import redmapper
import numpy as np, matplotlib.pyplot as plt
import healsparse as hsp, fitsio, h5py, healpy as hp
import os, re, time, glob, joblib, textwrap, shutil, yaml, pathlib
from tqdm import tqdm
from pkg_resources import resource_filename

from . import utils
import elidestools as etools

rm_version = redmapper.__version__


def timeit(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        total_time = end_time - start_time
        print('='*100)
        print(f"Function <<{func.__name__}>> took {total_time:.5} seconds to run.")
        print('='*100)
        return result
    return wrapper


class BaseRunner:

    def __init__(self, outBase, input_catalog_hdf5, input_specz,
                 fracdet_map, foreground_map, SPmap_path,
                 SPmap_names = ['maglim', 'fwhm', 'airmass', 'exptime', 'skybrite'],
                 seed = 42, calib_dir = None,
                 bands = ['U', 'G', 'R', 'I', 'Z', 'F106', 'F129', 'F158', 'F184'],
                 bands_inds = [0, 1, 2, 3, 4, 5, 6, 7, 8],
                 survey  = 'roman',
                 refband = 'F184',
                 n_jobs = 32, nside_split = 32,
                 Nrandoms = 1_000_000,
                 z_range  = [0.1, 0.95],
                 color_presel_thresh = [0.2]*9,
                 config_override = None,
                 zeropoint = 22.5):
        
        """
        Initialize the Redmapper pipeline

        Parameters
        ----------
        outBase : str
            Base path or prefix for all output files generated by the pipeline.

        input_catalog_hdf5 : str
            Path to the input galaxy catalog in HDF5 format containing photometric
            and positional information.

        input_specz : str or array-like
            Path to, or array containing, spectroscopic redshift information for
            the input catalog.

        fracdet_map : str
            Path to the HEALPix fractional detection (coverage) map used to mask
            or weight objects based on survey completeness.

        foreground_map : str
            Path to a HEALPix map describing foreground contamination (e.g.,
            Galactic extinction or other systematics).

        SPmap_path : str
            Directory containing survey property (SP) maps.

        SPmap_names : list of str, optional
            Names of the survey property maps to load from `SPmap_path`. These
            typically correspond to observing conditions such as magnitude limit,
            seeing (FWHM), airmass, exposure time, and sky brightness.
            Default is ['maglim', 'fwhm', 'airmass', 'exptime', 'skybrite'].

        seed : int, optional
            Random seed used for reproducible operations such as random catalog
            generation. Default is 42.

        calib_dir : str or None, optional
            Path to calibration data used for photometric or survey calibration.
            If None, no external calibration files are used. This is useful
            only if you want to run redmapper on Dataset A using calibration
            run on dataset B. Rarely needed.

        bands : list of str, optional
            List of photometric bands present in the catalog and survey property
            maps. Default corresponds to Roman-like bands.

        bands_inds : list of int, optional
            Indices corresponding to the band ordering used internally in the
            input catalog.

        survey : str, optional
            Name of the survey configuration being simulated or processed
            (e.g., 'roman', 'lsst'). Default is 'roman'.

        refband : str, optional
            Reference band used for magnitude selections or depth cuts.
            Default is 'F184'.

        n_jobs : int, optional
            Number of parallel jobs to use for processing tasks such as map
            evaluations or catalog operations. Default is 32.

        nside_split : int, optional
            HEALPix `nside` used to split the sky into regions for parallel
            processing. Default is 32.

        Nrandoms : int, optional
            Number of random points to generate when constructing random catalogs
            for the cluster catalog. Default is 1,000,000.

        z_range : list, optional
            The minimum and maximum redshift to consider for the cluster candidate.

        color_presel_thresh: list, optional
            The threshold in, abs(mag_obs - model) < thresh, that is used to preselect
            red-ish galaxies to send to redmapper in the first place. It has dimensions
            of 1 - Nbands, and is organized as [m1 - m2, m2 - m3, ....] where mi is a
            mag in a band in the same order passed in the bands input.

        config_override: path/str, optional
            A path to the config.yaml file that tells us updated values for any
            params in the default redmapper config from Eli. If you want to update
            a value, make sure you use the same naming format as Eli's default configs:
            https://github.com/DhayaaAnbajagane/redmapper/blob/main/how-to/cal_example.yml

        zeropoint: float, optional
            The zeropoint of the fluxes in the flux-2-mag conversion. Defaults to 22.5
            based on Chun-Hao To's definitions for Roman.
        """
        
        self.outBase    = outBase
        self.seed       = seed
        self.calib_dir  = calib_dir
        self.bands      = bands
        self.bands_inds = bands_inds
        self.refband    = refband
        self.refbandind = bands_inds[bands.index(refband)]
        self.n_jobs     = n_jobs
        self.survey     = survey
        self.Nrandoms   = Nrandoms
        self.z_range    = z_range
        

        self.input_catalog_hdf5   = input_catalog_hdf5
        self.input_specz          = input_specz
        self.fracdet_map          = fracdet_map
        self.foreground_map       = foreground_map
        self.SPmap_path           = SPmap_path
        self.SPmap_names          = SPmap_names
        self.nside_split          = nside_split
        self.color_presel_thresh  = color_presel_thresh
        self.config_override      = config_override
        self.zp                   = zeropoint

        if self.calib_dir != None:
            if self.calib_dir[-1] == '/':
                self.calib_dir = self.calib_dir[:-1]
                print("Removing backspace from calib_dir")

                

    @timeit
    def go(self):

        self.prep_training_catalog(n_jobs = self.n_jobs)
        self.make_all_maps()
        self.make_master_galaxy_catalog()
        self.make_spec_catalog_redseq()
        self.make_config_yaml()
        self.run_redmapper_calibration()
        self.run_zred_pixel()
        self.run_zred_bkg()
        self.run_redmapper_pixel()
        self.consolidate_redmapper_pixel()
        self.make_randoms()
        self.make_redmagic()
        
    @timeit
    def prep_training_catalog(self, n_jobs):
        
        #outpath should be whatever format is utilized in RomanCollator
        
        Collator = utils.RomanCollator(self.outBase, n_jobs = n_jobs, nside = self.nside_split, bands = self.bands)
        Collator.run(self.input_catalog_hdf5)


    @timeit
    def make_all_maps(self):

        self.make_area_mask()
        self.make_depth_map()
        self.make_depth_str_map()

    
    @timeit
    def get_fracdet_map(self):

        return hp.read_map(self.fracdet_map)
    
    @timeit
    def get_foreground_map(self):

        return hp.read_map(self.foreground_map)
    
    def get_NSIDE(self):
        
        return hp.npix2nside(self.get_fracdet_map().size)

    @timeit
    def make_area_mask(self):

        if os.path.isfile(self.outBase + '.roman_pixmask.hs'):
            print("PIX FILES ALREADY EXISTS. SKIPPING....")
            return None
        
        footprint  = self.get_fracdet_map()
        foreground = self.get_foreground_map()
        NSIDE      = hp.npix2nside(foreground.size)
        
        footprint  = footprint.astype(np.float32)
        foreground = foreground.astype(np.float32)
         

        assert footprint.size == foreground.size, f"Footprint ({footprint.size}) and Foreground ({foreground.size}) maps have different sizes"
        assert NSIDE > 32, f"You have NSIDE = {NSIDE} <= 32. We need map to be more fine-grained than the healsparse coarse gain resolution"

        print("LOADED FOOTPRINT AND FOREGROUND MASKS")

        #Zero out pixels with too low coverage
        #and pixels that are outside foreground mask
        footprint[footprint < 0.5] = hp.UNSEEN
        footprint[foreground > 0]  = hp.UNSEEN

        print("APPLY FOREGROUND MASK AND FRACGOOD > 0.5")

        hsmask    = hsp.HealSparseMap.make_empty(32, NSIDE, dtype = np.float32)
        hsmask[:] = footprint[hp.nest2ring(NSIDE, np.arange(foreground.size))].astype(np.float32)

        hsmask.write(self.outBase + '.roman_pixmask.hs', clobber = True)
        hp.write_map(self.outBase + '.roman_pixmask.hpy', hsmask.generate_healpix_map(NSIDE, nest = False), overwrite = True)

        print("WROTE TO DISK...")


    @timeit
    def make_depth_map(self, n_jobs = -1):

        self.compute_depth_pixel_process(n_jobs)
        self.prepare_sys_maps()
        self.compute_depth_map()
        self.compute_exp_limit()


    @timeit
    def prepare_sys_maps(self):

        print("CHECKING THAT MAPS EXIST")
        for b in self.bands:
            for sys in self.SPmap_names:

                path     = self.SPmap_path + "_%s_%s.hpy" % (b, sys)
                path_out = path.replace(os.path.dirname(self.SPmap_path), os.path.dirname(self.outBase))
                assert os.path.isfile(path), f"The map not found at: {path}"

                if not os.path.isfile(path_out):
                    shutil.copy(path, path_out)

        print("MAKING FRACGOOD MAPS FOR SYSMAP PROCESSING")

        path = os.path.dirname(self.outBase) + "/" +  os.path.basename(self.SPmap_path) + f'_{self.bands[-1]}_frac.hpy'
        if os.path.isfile(path):
            print("FRACMAPS EXIST. SKIPPING..")
        else:
            print("MAPS FOR FINAL BAND IS MISSING, REMAKING THEM ALL TO BE SAFE....")
            NSIDE    = self.get_NSIDE()
            FRACGOOD = hsp.HealSparseMap.read(self.outBase + '.roman_pixmask.hs')
            FRACGOOD = FRACGOOD.fracdet_map(nside=NSIDE)
            FRACGOOD = FRACGOOD.generate_healpix_map(nside = NSIDE, nest = False)
            for b in self.bands: 
                path = os.path.dirname(self.outBase) + "/" +  os.path.basename(self.SPmap_path) + f'_{b}_frac.hpy'
                print(path)
                hp.write_map(path, FRACGOOD, overwrite = True)



    @timeit
    def compute_depth_pixel_process(self, n_jobs = -1):

        filelist = sorted(glob.glob(self.outBase + '_pix*_flux.fits')) #Get all files by checking for flux fits
        filelist = [f[:-10] for f in filelist] #Remove the _flux.fits part of the filename
        filelist = [filelist[i] for i in np.random.choice(len(filelist), len(filelist), replace = False)] #Randomize to balance the load
        
        if n_jobs == -1: n_jobs = np.min([os.cpu_count(), len(filelist)])

        print(f"RUNNING {len(filelist)} PIXELS USING {n_jobs} JOBS", flush = True)

        jobs = [joblib.delayed(self._single_step_pixel_process)(f) for f in filelist]
        out  = joblib.Parallel(n_jobs = n_jobs, verbose = 10)(jobs)


    def _single_step_pixel_process(self, path):
        
        if os.path.isfile(path.replace('_flux.', '.')):
            print(f"PATH {path} EXISTS. SKIPPING PROCESS STEP....", flush = True)
        
        etools.des_depth.catalogPixelProcess(path, self.outBase, 'flux', 'flux', 'fluxerr', 1024, zp = self.zp,
                                             nSidePixFile = self.nside_split, bandList = self.bands, noGoldFlags = True, 
                                             s2nCut = 5, selectGalaxies = True, bdSizeFileType = None, nTrial = 3)



    @timeit
    def compute_depth_map(self):

        NSIDE = self.get_NSIDE()
        if os.path.isfile(self.outBase + f'_nside{NSIDE}_nest_{self.bands[-1]}_depth.fits.gz'):
            print("FILES FOUND. SKIPPING....")
            return None

        files = glob.glob(self.outBase + '_pix?????.fits')
        print(f"FOUND {len(files)} PIXEL FILES. CONSOLATING.....")
        etools.des_depth.pixelConsolidate(files, self.outBase + '_coarse_depth.fits', nSide = 1024, nest = False)
        print("FINISHED CONSOLIDATING. MAKING DEPTH MAP....")

        altbands = [self.bands[-2], self.bands[-3]] if len(self.bands) >= 3 else self.bands
        mapMaker = etools.des_depth.MakeMap(self.outBase + '_coarse_depth.fits', os.path.dirname(self.outBase),
                                            os.path.basename(self.SPmap_path) + "_%s_%s.hpy", self.outBase,
                                            maglimType = 'maglim',
                                            sysTypes = [x for x in self.SPmap_names if x != 'maglim'],
                                            bands    = self.bands,
                                            altBands = altbands,
                                            aLambda  = None,
                                            npixFit  = [1] * len(self.bands),
                                            maxTry   = 3)
        mapMaker.run()


    @timeit
    def compute_exp_limit(self):

        if os.path.isfile(self.outBase + '_coarse_depth_teff.fits'):
            print("FOUD COARSE_DEPTH_TEFF FILE. SKIPPING....")
            return None

        etools.des_depth.expLimit(self.outBase + '_coarse_depth.fits', self.bands, npixMax = [5] * len(self.bands))


    @timeit
    def make_depth_str_map(self):

        if os.path.isfile(self.outBase + f'-10{self.bands[-1]}_flux_depthstr.hs'):
            pass
        else:
            zp      = self.zp

            hsmask  = hsp.HealSparseMap.read(self.outBase + '.roman_pixmask.hs')
            
            dtype   = [('exptime', 'f4'), ('limmag', 'f4'), ('m50', 'f4'), ('fracgood', 'f4')]

            teffstr, thdr = fitsio.read(self.outBase + '_coarse_depth_teff.fits', ext = 1, trim_strings = True, header = True, lower = True)
            pivot         = thdr['PIVOT']
            NSIDE         = self.get_NSIDE()

            for b in self.bands:

                if os.path.isfile(self.outBase + f'-10{b}_flux_depthstr.hs'):
                    print("FOUND DEPTH_STR FILE", self.outBase + f'-10{b}_flux_depthstr.hs', '. SKIPPING.....')
                    continue

                
                depthfile = self.outBase + f'_nside{NSIDE}_nest_{b}_depth.fits.gz'
                depthin   = hp.read_map(depthfile, nest = True)
                depth     = hsp.HealSparseMap.make_empty(32, NSIDE, dtype=np.float32)
                depth[:]  = depthin

                depth_pix = depth.valid_pixels
                ind       = list(teffstr['band']).index(b)

                dstr = np.zeros(depth_pix.size, dtype=dtype)
                dstr['limmag']   = depth[depth_pix]
                dstr['m50']      = depth[depth_pix]
                dstr['exptime']  = np.exp(teffstr[ind]['fit'][0] + teffstr[ind]['fit'][1]*(depth[depth_pix] - pivot))
                dstr['fracgood'] = hsmask[depth_pix]

                hsdepth = hsp.HealSparseMap.make_empty(nside_coverage = 32, nside_sparse = NSIDE, dtype = dtype, primary = 'fracgood')
                use,    = np.where(dstr['fracgood'] > 0.5)
                hsdepth[depth_pix[use]] = dstr[use]

                hdr = {}
                hdr['NSIG']  = 10.0
                hdr['ZP']    = self.zp
                hdr['NBAND'] = 1
                hdr['W']     = 0.0  # wall mode
                hdr['EFF']   = 1.0

                hsdepth.metadata = hdr
                hsdepth.write(self.outBase + f'-10{b}_flux_depthstr.hs', clobber = True)

                print(f"WROTE {b}_flux_depthstr.hs TO DISK")


        
    @timeit
    def make_master_galaxy_catalog(self):


        if os.path.isfile(self.outBase + "_master_table.fit"):
            print("FOUND MASTER TABLE. SKIPPING MAKE CATALOG...")
            return None

        widebase  = self.outBase
        outbase   = self.outBase
        maskfile  = self.outBase + '.roman_pixmask.hs'
        depthfile = self.outBase + f'-10{self.refband}_flux_depthstr.hs'

        mask  = hsp.HealSparseMap.read(maskfile)
        depth = hsp.HealSparseMap.read(depthfile)

        area  = np.sum(mask.get_values_pix(mask.valid_pixels), dtype=np.float64) * hp.nside2pixarea(mask.nside_sparse, degrees = True)

        print('Area = ', area)

        limmag_max = depth.get_values_pix(depth.valid_pixels)['limmag'].max()

        print('limmag_max = ', limmag_max)

        zp       = self.zp
        errrange =[0.0, 100.0]

        # b_array  = np.array([3.27e-12, 4.83e-12, 6.0e-12, 9.0e-12])
        b_array  = np.array([1.4e-12, 9.0e-13, 1.2e-12, 1.8e-12, 7.4e-12,7.4e-12,7.4e-12,7.4e-12,7.4e-12,7.4e-12])
        bscale   = np.array(b_array) * 10.**(zp / 2.5)
        refbands = ['U', 'G', 'R', 'I', 'Z', 'Y', 'F106', 'F129', 'F158', 'F184']

        bands    = self.bands
        nmag     = len(bands)
        ref_ind  = bands.index(self.refband)

        redmapper_dtype = [ ('id', 'i8'),              # galaxy id number (unique)
                            ('ra', '>f8'),             # right ascension (degrees)
                            ('dec', '>f8'),            # declination (degrees)
                            ('refmag', '>f4'),         # total magnitude in reference band
                            ('refmag_err', '>f4'),     # error in total reference mag
                            ('mag', '>f4', nmag),      # mag array
                            ('mag_err', '>f4', nmag),  # magnitude error array
                            ('ebv', '>f4')]            # E(B-V) (systematics checking)
        info_dict = {}
        info_dict['LIM_REF'] = limmag_max
        info_dict['REF_IND'] = ref_ind
        info_dict['AREA']    = area
        info_dict['NMAG']    = nmag
        info_dict['MODE']    = self.survey.upper() # currently SDSS, DES, or LSST
        info_dict['ZP']      = zp
        info_dict['B']       = np.array([b_array[refbands.index(b.upper())] for b in self.bands]) # if magnitudes are actually luptitudes

        for b, i in zip(self.bands, self.bands_inds):
            info_dict[f'{b.upper()}_IND'] = i
    
        widefiles = sorted(glob.glob('%s_pix*_basic.fits' % (widebase)))
        maker     = redmapper.GalaxyCatalogMaker(outbase, info_dict)

        offset    = 0
        for input_file in tqdm(widefiles, desc = 'collating files'):
            
            # make all 4 mags, combining
            #   sof (wide)
            #   luptitudification

            groups = re.search('_pix(\d+)_', os.path.basename(input_file))
            pixnum = int(groups[1])

            basic  = fitsio.read(input_file, ext=1, lower=True)
            fflux  = fitsio.read(input_file.replace('_basic.fits', '_flux.fits'), ext=1, lower=True)

            galaxies         = np.zeros(basic.size, dtype = redmapper_dtype)
            galaxies['id']   = offset + np.arange(len(galaxies))
            offset          += len(galaxies)
            galaxies['ra']   = basic['ra']
            galaxies['dec']  = basic['dec']

            for i, band in enumerate(bands):

                b_i     = refbands.index(band.upper())

                flux    = fflux['flux_%s' % (band.lower())].astype(np.float64)
                fluxerr = fflux['fluxerr_%s' % (band.lower())].astype(np.float64)

                galaxies['mag'][:, i]     = 2.5 * np.log10(1.0 / b_array[b_i]) - np.arcsinh(0.5 * flux / bscale[b_i]) / (0.4 * np.log(10.0))
                galaxies['mag_err'][:, i] = 2.5 * fluxerr / (2.0 * bscale[b_i] * np.log(10.0) * np.sqrt(1.0 + (0.5 * flux / bscale[b_i])**2.))


            galaxies['refmag']     = galaxies['mag'][:, ref_ind]
            galaxies['refmag_err'] = galaxies['mag_err'][:, ref_ind]
            #galaxies['ebv'] = basic['ebv_sfd98']

            # Mark bad objects
            mark = np.ones(galaxies.size, dtype=bool)
            bad, = np.where((galaxies['refmag_err'] < errrange[0]) |
                            (galaxies['refmag_err'] > errrange[1]))
            mark[bad] = 0

            for i, band in enumerate(bands):
                bad, = np.where((galaxies['mag'][:, i] < errrange[0]) |
                                (galaxies['mag'][:, i] > errrange[1]) | 
                                (galaxies['mag_err'][:, i] < errrange[0]) |
                                (galaxies['mag_err'][:, i] > errrange[1]))
                mark[bad] = 0

            # Apply depth maps
            m50 = depth.get_values_pos(galaxies['ra'], galaxies['dec'], lonlat=True)['m50']

            gd, = np.where((mark) & (galaxies['refmag'] < m50))

            if gd.size == 0:
                print("All galaxies too faint in pixel %d" % (pixnum))
                continue

            # And append the galaxies
            maker.append_galaxies(galaxies[gd])

        maker.finalize_catalog()


    @timeit
    def make_spec_catalog_redseq(self):
        
        if os.path.isfile(self.outBase + ".train_specz.fits"):
            print("FOUND TRAIN SPECZ CATALOG. SKIPPING MAKE CATALOG...")
            return None
            
        galaxy  = redmapper.galaxy.GalaxyCatalog.from_galfile(self.outBase + "_master_table.fit")
        allspec = fitsio.read(self.input_specz)
        MODEL   = fitsio.read(os.path.dirname(__file__) + f'/../calibdata/initcolors/bc03_colors_{self.survey}.fit')

        print("LOADED ALL CATALOGS")
        
        id1, id2, dist = galaxy.match_many(allspec['ra'], allspec['dec'], 0.5/3600, maxmatch = 1)

        allspec = allspec[id1]
        galmag  = galaxy.mag[id2]

        print(f"FINISHED MATCHING. FOUND {len(allspec)} MATCHES.")

        #Now plot the sequences
        use, = np.where(galmag[:, 0] > 0.0)
        
        assert np.all(np.diff(np.array(self.bands_inds)) == 1), \
            "Input bands are offset by more than 1 filter. You need to use a new file for this analysis....Ping Dhayaa"

        QAcut  = True
        for i in range(len(self.bands) - 1):
            THRESH= self.color_presel_thresh[i]
            data  = galmag[:, i] - galmag[:, i + 1]
            model = np.interp(allspec['z'][use], MODEL['Z'], MODEL['COLOR'][:, self.bands_inds[i]])
            QAcut = QAcut & (np.abs(model - data) <= THRESH)
        
        print(f"FINISHED CULLING. WE HAVE {len(use[QAcut])} MATCHES.")

        plt.close()
        for i in range(len(self.bands) - 1):
            THRESH= self.color_presel_thresh[i]
            plt.hexbin(allspec['z'][use], (galmag[:, i] - galmag[:, i + 1])[use], extent=[0, 1, 0.0, 2.5], bins='log')
            plt.xlabel('z'); plt.ylabel(f'{self.bands[i]} - {self.bands[i + 1]}')
            plt.plot(MODEL['Z'], MODEL['COLOR'][:, self.bands_inds[i]], 'b-')
            plt.plot(MODEL['Z'], MODEL['COLOR'][:, self.bands_inds[i]] + THRESH, 'b:')
            plt.plot(MODEL['Z'], MODEL['COLOR'][:, self.bands_inds[i]] - THRESH, 'b:')
            plt.savefig(self.outBase + f"_all_specz_z_{self.bands[i]}m{self.bands[i + 1]}.png"); plt.close()

        #Save the proper sample now
        fitsio.write(self.outBase + ".train_specz.fits", allspec[use[QAcut]], clobber = True)

        print("SAVED CUT CATALOG")
    

    @timeit
    def make_calibration_hpix(self):

        specz       = fitsio.read(self.outBase + ".train_specz.fits")
        hpix_specz  = np.unique(hp.ang2pix(self.nside_split, specz['ra'], specz['dec'], lonlat = True))

        print(f"{len(hpix_specz)} PIXELS HAVE SPECZ IN THEM")

        hpix_choice = sorted(glob.glob(self.outBase + '_pix?????.fits'))
        hpix_choice = [int(h[-10:-5]) for h in hpix_choice]
        hpix_choice = [h for h in hpix_choice if h in hpix_specz]
        np.random.default_rng(seed = self.seed).shuffle(hpix_choice)
        hpix_choice = hpix_choice[:int(len(hpix_choice) * 0.5)] #Use half of sample to calibrate

        return hpix_choice
    

    @timeit
    def make_config_yaml(self):
        
        hpix_choice = self.make_calibration_hpix()

        pin  = os.path.dirname(__file__) +  f'/../calibdata/mstar/mstar_{self.survey}_{self.refband}03.fit'
        pout = resource_filename('redmapper', f'data/mstar/mstar_{self.survey}_{self.refband}03.fit')
        shutil.copy(pin, pout)

        pin  = os.path.dirname(__file__) + f'/../calibdata/initcolors/bc03_colors_{self.survey}.fit'
        pout = resource_filename('redmapper', f'data/initcolors/bc03_colors_{self.survey}.fit')
        shutil.copy(pin, pout)

        print("COPIED COLOR CALIBRATION FILES INTO REDMAPPER SOURCE DIR")

        CONFIG = f"""
        # Galaxy file for input
        outpath: '{os.path.dirname(self.outBase)}'
        galfile: '{self.outBase + "_master_table.fit"}'

        redgalfile: '{self.outBase + "_zspec_redgals.fit"}'
        redgalmodelfile: '{self.outBase + "_zspec_redgals_model.fit"}'
        
        # Path to put plots in
        plotpath: '{os.path.dirname(self.outBase)}/plots'

        # Galaxy catalog has truth information (as with simulated catalogs)
        has_truth: False

        # Healpixel over which to run calibration
        # Set this and nside to 0 to run the full footprint
        hpix: {hpix_choice}
        # Nside of this healpix
        nside: {self.nside_split}
        # Should be set to 0 for calibration
        border: 0.0

        # Reference magnitude (band) name
        refmag: {self.refband}

        # Redshift range [lo, hi]
        zrange: {self.z_range}

        # Spectroscopic input catalog
        specfile: {self.input_specz}

        specfile_train: {self.outBase + ".train_specz.fits"}

        # All files will start with this name
        # If the name ends with "cal" it will be replaced with "run" for the runs
        outbase: my_roman

        # Maximum chi-squared to consider a possible member.  Default is 20.0
        chisq_max: 20.0

        # L* threshold for computing richness.  Default is optimal 0.2
        lval_reference: 0.2

        # Name of the "survey" for the m*(z) file
        # (see README.md for details)
        mstar_survey: {self.survey}
        # Name of the "band" for the m*(z) file
        mstar_band: {self.refband}03

        # Maximum weighted coverage area of a cluster to be masked before it
        # is removed from the catalog.  Default is 0.2
        max_maskfrac: 0.2

        # Number of sample galaxies to compute mask region.  Default is 6000
        maskgal_ngals: 6000
        # Number of different samples of maskgal_ngals (reduces biases at high redshift)
        maskgal_nsamples: 100
        # Filetype mode for the geometric mask.  Default is 0
        # Mode 3 is a healpix mask.  (only mode supported)
        mask_mode: 3
        # Name of the mask file.  See README.md for format.  Default is None
        maskfile: {self.outBase + '.roman_pixmask.hs'}

        # Name of the depth file.  See README.md for format.  Default is None
        depthfile: {self.outBase + f'-10{self.refband}_flux_depthstr.hs'}

        # chi-squared binsize for background.  Default is 0.5
        bkg_chisqbinsize: 0.5
        # reference mag binsize for background.  Default is 0.2
        bkg_refmagbinsize: 0.2
        # redshift binsize for background.  Default is 0.02
        bkg_zbinsize: 0.02
        # redshift binsize for zred background.  Default is 0.01
        bkg_zredbinsize: 0.01
        # Compute background down to the magnitude limit?  Default is False
        # This will be useful in the future when computing membership probabilities
        # for non-members (not supported yet).  If turned on, background
        # computation is slower (depending on depth).
        bkg_deepmode: False

        # Name of centering class for calibration first iteration.  Default is CenteringBCG
        firstpass_centerclass: CenteringBCG
        # Name of centering class for cluster runs.  Default is CenteringWcenZred
        centerclass: CenteringWcenZred

        # Number of iterations for calibration.  Default is 3
        calib_niter: 3
        # Number of cores on local machine for calibration (zred, background)
        # Default is 1
        calib_nproc: {self.n_jobs}
        # Number of cores on local machine for calibration cluster finder runs
        # Default is 1
        calib_run_nproc: {self.n_jobs}

        # Nsig for consistency with red sequence to be used in red-sequence calibration.  Default is 1.5
        #  Make this too wide, and blue galaxies contaminate the red sequence width computation.
        #  Make this too narrow, and there is not enough signal.  Empirically, 1.5 works well.
        calib_color_nsig: 1.5
        # Nsig for consistence with red sequence to be used as a training seed galaxy.  Default is 2.0
        calib_redspec_nsig: 2.0

        # Red-sequence color template file for initial guess of red sequence.
        calib_redgal_template: bc03_colors_{self.survey}.fit
        # Redshift spline node spacing for red-sequence pivot magnitude
        # Default is 0.1
        calib_pivotmag_nodesize: 0.1
        # Redshift spline node spacing for each color.  Must be array of length nmag - 1
        # Recommended default is 0.05 for each color
        calib_color_nodesizes: {[0.05] * (len(self.bands) - 1)}
        # Redshift spline node spacing for each slope.  Must be array of length nmag - 1
        # Recommended default is 0.1 for each color slope
        calib_slope_nodesizes: {[0.1] * (len(self.bands) - 1)}
        # Maximum redshift for spline to use in fit.
        # Recommended is -1 (max redshift) for each color, unless a band is very shallow/blue
        # (for SDSS, only consider u-g in detail at z<0.4)
        calib_color_maxnodes: {[-1] * (len(self.bands) - 1)}
        # Maximum redshift for covariance spline to use in fit.
        # Recommended is -1 (max redshift) for each color, unless a band is very shallow/blue
        # (For SDSS, only consider u-g in detail in covmat at z<0.4)
        calib_covmat_maxnodes: {[-1] * (len(self.bands) - 1)}
        # Redshift spline node spacing for covariance matrix.  Default is 0.15
        calib_covmat_nodesize: 0.25

        calib_covmat_constant: 0.9

        # Redshift spline node spacing for zred corrections.  Default is 0.05
        calib_corr_nodesize: 0.1
        # Redshift spline node spacing for zred slope corrections.  Default is 0.1
        calib_corr_slope_nodesize: 0.2

        # Use "pcol" (which excludes radial weight) in selecting galaxies to calibrate the
        #  red sequence.  Default is True, which is strongly recommended.
        calib_use_pcol: True
        # Membership probability cut to compute zred corrections.  Default is 0.9
        calib_corr_pcut: 0.8
        # Membership probability cut for pivotmag and median color computation.  Default is 0.7
        calib_color_pcut: 0.5

        # Membership probability cut for use in red-sequence calibration.  Default is 0.3
        calib_pcut: 0.3
        # Minimum richness for a cluster to be considered a calibration cluster.  Default is 5.0
        calib_minlambda: 5.0
        # Smoothing kernel on redshifts from calibration clusters.  Default is 0.003
        calib_smooth: 0.003

        # Luminosity function filter alpha parameter.
        calib_lumfunc_alpha: -1.0

        # Zeroth iteration color training parameters

        # Scale radius of radius/richness relation (r_lambda = r0 * (lambda/100)^beta)
        # Default is 0.5 (h^-1 Mpc)
        calib_colormem_r0: 0.5
        # Power-law slope of radius/richness relation
        # Default is 0.0
        calib_colormem_beta: 0.0
        # Smoothing kernel on redshifts from color calib clusters.  Default is 0.003
        calib_colormem_smooth: 0.003
        # Minimum richness to be used as a color-training cluster.  Default is 10.0
        calib_colormem_minlambda: 10.0
        # Color indices for training, redshift bounds, and assumed intrinsic scatter.
        # For the following settings:
        #  Low redshift: z<0.35, use color index 1 (g-r), intrinsic scatter 0.05
        #  Middle redshift: 0.5<z<0.72, use color index 2 (r-i), intrinsic scatter 0.03
        #  High redshift: z>0.72, use color index 3 (i-z), intrinsic scatter 0.03
        # (Note that the high redshift one is not used if zrange[1] = 0.60)
        calib_colormem_colormodes: {list(range(len(self.bands) - 1))}
        calib_colormem_zbounds: [0.35, 0.8]
        calib_colormem_sigint: [0.05, 0.03, 0.03]

        # Cluster photo-z z_lambda parameters

        # Redshift spline spacing for correcting cluster z_lambda.  Default is 0.04
        calib_zlambda_nodesize: 0.1
        # Redshift spline spacing for richness slope correction of cluster z_lambda.
        # Default is 0.1
        calib_zlambda_slope_nodesize: 0.1
        # Minimum richness for computing z_lambda correction.  Default is 20.0
        calib_zlambda_minlambda: 5.0
        # Number of z_lambda_e sigma an outlier can be to be included in correction
        # Default is 5.0
        calib_zlambda_clean_nsig: 3.5
        # Number of iterations for z_lambda correction algorithm.  Default is 3
        calib_zlambda_correct_niter: 3

        # Pivot richness for richness correction.  Default is 30.0
        zlambda_pivot: 30.0
        # Bin size for interpolating z_lambda correction.  Default is 0.002
        zlambda_binsize: 0.002
        # Tolerance for convergence when computing z_lambda.  Default is 0.0002
        zlambda_tol: 0.0002
        # Maximum number of iterations to converge to z_lambda.  Default is 20
        zlambda_maxiter: 20
        # Fraction of highest probability members to use to compute z_lambda.  Default is 0.7
        zlambda_topfrac: 0.7
        # Step size to fit a parabola to peak of z_lambda likelihood.  Default is 0.002
        zlambda_parab_step: 0.002
        # Epsilon size to compute change in richness as a function of redshift.  Default is 0.005
        zlambda_epsilon: 0.005

        # Centering parameters

        # Pivot richness for wcen model.  Default is 30.0
        wcen_pivot: 30.0
        # Minumum richness to use in calibrating wcen model.  Default is 10.0
        wcen_minlambda: 10.0
        # Maximum richness to use in calibrating wcen model.  Default is 100.0
        wcen_maxlambda: 100.0
        # Softening radius (h^-1 Mpc) in computing wcen.  Default is 0.05
        wcen_rsoft: 0.05
        # Richness range for calibrating wcen model.
        #  This should be within the volume-limited range of the catalog.
        wcen_cal_zrange: [0.2, 0.65]
        
        
        # Cluster finder: first pass

        # r0 in radius-richness relation (see above).  Default is 0.5 (h^-1 Mpc)
        firstpass_r0: 0.5
        # beta in radius-richness relation.  Default is 0.0
        firstpass_beta: 0.0
        # Number of iterations in first pass.  Default is 2
        firstpass_niter: 2
        # Minimum richness to pass cluster candidate to next step.  Default is 3.0
        firstpass_minlambda: 3.0

        # Cluster finder: Likelihood pass

        # r0 is radius-richness relation (see above).  Default is 1.0 (h^-1 Mpc)
        #  Note that these should typically be the same as used in percolation
        likelihoods_r0: 1.0
        # beta in radius-richness relation.  Default is 0.2
        likelihoods_beta: 0.2
        # Should likelihood use the zred in computing likelihood.  Default is True
        likelihoods_use_zred: True
        # Minimum richness to pass cluster candidate to next step.  Default is 3.0
        likelihoods_minlambda: 3.0

        # Cluster finder: Percolation pass

        # r0 is radius-richness relation (see above).  Default is 1.0 (h^-1 Mpc)
        #  Note that these should typically be the same as used in likelihood
        percolation_r0: 1.0
        # beta in radius-richness relation.  Default is 0.2
        percolation_beta: 0.2
        # rmask_0 in rmask = rmask_0 * (lambda / 100) ^ rmask_beta * (z_lambda / rmask_zpivot)^rmask_gamma
        #  relation.  This sets the radius to which member galaxies are masked in percolation.
        #  This should be >= percolation_r0.  Default is 1.5
        percolation_rmask_0: 1.95
        # beta in rmask relation
        percolation_rmask_beta: 0.45
        # gamma in rmask relation
        percolation_rmask_gamma: 0.0
        # zpivot in rmask relation
        percolation_rmask_zpivot: 0.3
        # Mask galaxies down to this luminosity cut (fainter than richness computation).  Default is 0.1 (L*)
        percolation_lmask: 0.1
        # Number of iterations to compute richness/redshift in percoltation.  Default is 2
        percolation_niter: 2
        # Minimum richness to save cluster.  Default is 3.0
        percolation_minlambda: 3.0
        # Minimum probability of being a bcg for a galaxy to be considered a center.  Default is 0.5
        percolation_pbcg_cut: 0.5
        # Maximum number of possible centrals to record.  Default is 5
        percolation_maxcen: 5


        vlim_depthfiles: {[self.outBase + f'-10{b}_flux_depthstr.hs' for b in self.bands]}
        vlim_bands: {[b for b in self.bands]}
        vlim_nsigs: {[4.0] * len(self.bands)}
        """
        
        with open(self.outBase + '_config.yaml', 'w') as f:
            f.write(textwrap.dedent(CONFIG))


        #Parameters that should not be updated by external user as
        #they are all set internall for a given run using data
        #the user provided at the very start.
        WARN_PARS = [
            'outpath',
            'galfile',
            'redgalfile',
            'redgalmodelfile',
            'plotpath',
            'hpix',
            'nside',
            'refmag',
            'zrange',
            'specfile',
            'specfile_train',
            'mstar_survey',
            'mstar_band',
            'maskfile',
            'depthfile',
            'calib_nproc',
            'calib_run_nproc',
            'calib_redgal_template',
        ]

        if self.config_override is not None:
            assert isinstance(self.config_override, str), f"Config must be a string path, you passed {self.config_override}"
            self._update_yaml(self.outBase + '_config.yaml', self.config_override, warn_on = WARN_PARS)


    def _update_yaml(self, current_cfg, updated_cfg, warn_on=None):
        """
        Update current_cfg in place using entries from updated_cfg.

        warn_on can contain either leaf names:
            {"catfile", "zredfile"}

        or full dotted paths:
            {"paths.catfile", "calib.zredfile"}
        """
        warn_on = set(warn_on or [])

        class FlowListDumper(yaml.SafeDumper):
            pass

        def _repr_list_flow(dumper, data):
            return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)

        FlowListDumper.add_representer(list, _repr_list_flow)

        with open(current_cfg, "r") as f:
            current = yaml.safe_load(f)

        with open(updated_cfg, "r") as f:
            updated = yaml.safe_load(f)

        def merge(current, updated, prefix=""):
            for k, v in updated.items():
                name = f"{prefix}.{k}" if prefix else str(k)

                if isinstance(v, dict) and isinstance(current.get(k), dict):
                    merge(current[k], v, name)
                else:
                    old = current.get(k, "<MISSING>")

                    if old != v:
                        print(f"{name}: {old} -> {v}")

                        if name in warn_on or str(k) in warn_on:
                            print("\n" + "!" * 90)
                            print(f"WARNING: OVERRIDING PARAM [{name}] THAT IS SELF-CONSISTENTLY SET IN REDMAPPER")
                            print(f"DOUBLE-CHECK THAT YOU REALLY WANT TO OVERRIDE IT")
                            print(f"OLD: {old}")
                            print(f"NEW: {v}")
                            print("!" * 90 + "\n")

                    current[k] = v

        merge(current, updated)

        with open(current_cfg, "w") as f:
            yaml.dump(current, f, Dumper=FlowListDumper, sort_keys=False)
        
            
    def _get_outbase_name(self):
        with open(self.outBase + '_config.yaml', "r") as f:
            current = yaml.safe_load(f)
            return current['outbase']
    
            
    @timeit
    def run_redmapper_calibration(self):

        if self.calib_dir is None:
            calib = redmapper.calibration.RedmapperCalibrator(self.outBase + '_config.yaml')
            calib.run()
        else:
            obase = self._get_outbase_name()
            shutil.copy(self.calib_dir + f'_run/{obase}_run_bkg.fit',         
                        os.path.dirname(self.outBase) + f'_run/{obase}_run_bkg.fit')
            shutil.copy(self.calib_dir + f'/{obase}_bkg_color.fit',           
                        os.path.dirname(self.outBase) + f'/{obase}_bkg_color.fit')
            shutil.copy(self.calib_dir + f'/{obase}_iter3_pars.fit',          
                        os.path.dirname(self.outBase) + f'/{obase}_iter3_pars.fit') 
            shutil.copy(self.calib_dir + f'/{obase}_zspec_redgals_model.fit', 
                        os.path.dirname(self.outBase) + f'/{obase}_zspec_redgals_model.fit') 
            shutil.copy(self.calib_dir + f'/{obase}_iter3_wcen.fit',          
                        os.path.dirname(self.outBase) + f'/{obase}_iter3_wcen.fit') 
            shutil.copy(self.calib_dir + f'/{obase}_iter3_zlambda.fit',       
                        os.path.dirname(self.outBase) + f'/{obase}_iter3_zlambda.fit') 
            print("COPIED REDMAPPER CALIBRATION OVER FROM", self.calib_dir)

    @timeit
    def run_zred_pixel(self, n_jobs = -1):
    
        dirname  = os.path.dirname(self.outBase)
        basename = os.path.basename(self.outBase)
        outpath  = f"{dirname}_run/zreds/{basename}_zreds_master_table.fit"

        if os.path.isfile(outpath):
            print("FOUND ZRED MASTER TABLE AT", outpath, "SKIPPING....")
            return None
        

        filelist = sorted(glob.glob(self.outBase + '_pix*_flux.fits')) #Get all files by checking for flux fits
        pixlist  = [int(f[-15:-10]) for f in filelist] #Get only the pixel part of the name
        pixlist  = [pixlist[i] for i in np.random.choice(len(pixlist), len(pixlist), replace = False)] #Randomize to balance the load
        
        print(pixlist)
        print(filelist)

        if n_jobs == -1: n_jobs = np.min([os.cpu_count(), len(filelist)])

        print(f"RUNNING {len(pixlist)} PIXELS USING {n_jobs} JOBS", flush = True)

        jobs = [joblib.delayed(self._single_step_zred_pixel)(p) for p in pixlist]
        out  = joblib.Parallel(n_jobs = n_jobs, verbose = 10)(jobs)

    
    def _single_step_zred_pixel(self, pix):

        runZredPixelTask = redmapper.pipeline.RunZredPixelTask(os.path.dirname(self.outBase) + '_run/run_default.yml', 
                                                               pix, self.nside_split, path = os.path.dirname(self.outBase))
        runZredPixelTask.run()


    @timeit
    def run_zred_bkg(self):

        config = redmapper.Configuration(os.path.dirname(self.outBase) + '_run/run_default.yml')
        zb     = redmapper.ZredBackgroundGenerator(config)
        zb.run()


    @timeit
    def run_redmapper_pixel(self, n_jobs = None):

        n_jobs   = self.n_jobs if n_jobs is None else n_jobs
        filelist = sorted(glob.glob(self.outBase + '_pix*_flux.fits')) #Get all files by checking for flux fits
        pixlist  = [int(f[-15:-10]) for f in filelist] #Get only the pixel part of the name
        pixlist  = [pixlist[i] for i in np.random.choice(len(pixlist), len(pixlist), replace = False)] #Randomize to balance the load
        
        #Find which hpix we have zreds for. Even though we start with the full catalog
        #We subselect and only run on regions with foreground mask (and fracgood) set.
        #So this figures out which coarse pixels can still be used.
        hpixlist = sorted(glob.glob(f"{os.path.dirname(self.outBase)}_run/zreds/*zreds_???????.fit"))
        hpixlist = [int(f[-11:-4]) for f in hpixlist]; print(hpixlist)
        # hpixlist = hp.ang2pix(8, *hp.pix2ang(32, hpixlist)); print(hpixlist)

        pixlist  = [p for p in pixlist if p in hpixlist]
        

        if n_jobs == -1: n_jobs = np.min([os.cpu_count(), len(filelist)])

        print(f"RUNNING {len(pixlist)} PIXELS (OUT OF POSSIBLE {len(filelist)}) USING {n_jobs} JOBS", flush = True)

        jobs = [joblib.delayed(self._single_step_run_redmapper_pixel)(p) for p in pixlist]
        out  = joblib.Parallel(n_jobs = n_jobs, verbose = 10)(jobs)

    
    def _single_step_run_redmapper_pixel(self, pix):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f'/{obase}_run_{self.nside_split}_{pix:05d}_final_catalog.fit'):
            print("HPIX RUN EXISTS. SKIPPING.....")
            return None
        
        runRedmapperPixelTask = redmapper.pipeline.RunRedmapperPixelTask(os.path.dirname(self.outBase) + '_run/run_default.yml', 
                                                                         pix, self.nside_split, path = os.path.dirname(self.outBase))
        runRedmapperPixelTask.run()


    @timeit
    def consolidate_redmapper_pixel(self):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f"/{obase}_run_redmapper_v{rm_version}_lgt05_vl02_catalog.fit"):
            print("FILE EXISTS. SKIPPING.....")
            return None
        
        consolidate = redmapper.pipeline.RedmapperConsolidateTask(os.path.dirname(self.outBase) + '_run/run_default.yml')
        consolidate.run()


    @timeit
    def make_randoms(self):

        config = os.path.dirname(self.outBase) + '/zmask02/zmask02.yml'

        self.setup_random_run(config)
        self.generate_randoms(config)
        self.redmapper_randoms_zmask(config)
        self.weight_randoms(config)


    @timeit
    def setup_random_run(self, config_path):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f"/zmask02/{obase}_run_redmapper_{rm_version}_vl02_vlim_zmask.fit"):
            print("FILES EXIST. SKIPPING....")
            return None
        
        #Make a new directory and duplicate config files
        os.makedirs(os.path.dirname(config_path), exist_ok = True)
        run_config  = os.path.dirname(self.outBase) + '_run/run_default.yml'
        rand_config = config_path
        shutil.copy(run_config, rand_config)
        
        #Rewrite lines in config
        path = pathlib.Path(rand_config)
        data = yaml.safe_load(path.read_text())
        data["catfile"]  = os.path.dirname(self.outBase) + f"/{obase}_run_redmapper_v{rm_version}_lgt05_vl02_catalog.fit"
        data["randfile"] = os.path.dirname(self.outBase) + f"/zmask02/{obase}_randoms_master_table.fit"
        path.write_text(yaml.safe_dump(data, sort_keys=False))

        config = redmapper.Configuration(rand_config)

        #Move zmask file over
        shutil.copy(os.path.dirname(self.outBase) + f"/{obase}_run_redmapper_v{rm_version}_vl02_vlim_zmask.fit", 
                    os.path.dirname(self.outBase) + "/zmask02/")


    @timeit
    def generate_randoms(self, config):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f"/zmask02/{obase}_randoms_master_table.fit"):
            print("FILES EXIST. SKIPPING....")
            return None
        
        #Run Step 6.1
        generateRandoms = redmapper.GenerateRandoms(redmapper.Configuration(config))
        generateRandoms.generate_randoms(self.Nrandoms)


    @timeit
    def redmapper_randoms_zmask(self, config, n_jobs = None):

        n_jobs   = self.n_jobs if n_jobs is None else n_jobs
        filelist = sorted(glob.glob(os.path.dirname(config) + '/*randoms_???????.fit')) #Get all files by checking for flux fits
        pixlist  = [int(f[-11:-4]) for f in filelist] #Get only the pixel part of the name
        pixlist  = [pixlist[i] for i in np.random.choice(len(pixlist), len(pixlist), replace = False)] #Randomize to balance the load
        
        if n_jobs == -1: n_jobs = np.min([os.cpu_count(), len(filelist)])

        print(f"RUNNING {len(pixlist)} PIXELS (OUT OF POSSIBLE {len(filelist)}) USING {n_jobs} JOBS", flush = True)

        jobs = [joblib.delayed(self._single_step_run_zmask_pixel)(p, config) for p in pixlist]
        out  = joblib.Parallel(n_jobs = n_jobs, verbose = 10)(jobs)

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f'/{obase}_run_redmapper_v{rm_version}_randoms_zmask_catalog.fit'):
            print("Consolidated file exists. Skipping.....")
            return None

        consolidate = redmapper.pipeline.RuncatConsolidateTask(config)
        consolidate.run(do_plots = False, match_spec = False, consolidate_members = False, cattype = 'randoms_zmask')

    
    def _single_step_run_zmask_pixel(self, pix, config):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f'/{obase}_run_{self.nside_split}_{pix:05d}_randoms_zmask_catalog.fit'):
            return None
        
        runRedmapperPixelTask = redmapper.pipeline.RunZmaskPixelTask(config, pix, self.nside_split, path = os.path.dirname(self.outBase))
        runRedmapperPixelTask.run()


    @timeit
    def weight_randoms(self, config):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f'/{obase}_run_redmapper_v{rm_version}_weighted_randoms_z010-095_lgt020_vl02_area.fit'):
            print("FILES EXIST. SKIPPING...")
            return None
        
        randfile = os.path.dirname(self.outBase) + f'/{obase}_run_redmapper_v{rm_version}_randoms_zmask_catalog.fit'

        config   = redmapper.Configuration(config)
        weigher  = redmapper.RandomWeigher(config, randfile)
        for lambda_cut in [5, 20]:
            wt_randfile, wt_areafile = weigher.weight_randoms(lambda_cut)

            print("Made weighted random file %s" % (wt_randfile))
            print("Made weighted area file %s" % (wt_areafile))


    @timeit
    def make_redmagic(self):

        self.calibrate_redmagic()
        self.generate_redmagic()


    @timeit
    def calibrate_redmagic(self):

        obase = self._get_outbase_name()
        if os.path.isfile(os.path.dirname(self.outBase) + f'/redmagic/{obase}_run_redmagic_calib.fit'):
            print("File exists. Skipping....")
            return None

        #Make a new directory and duplicate config files
        os.makedirs(os.path.dirname(self.outBase) + '/redmagic', exist_ok = True)
        run_config  = os.path.dirname(self.outBase) + '_run/run_default.yml'
        rmgc_config = os.path.dirname(self.outBase) + '/redmagic/run_default.yml'
        shutil.copy(run_config, rmgc_config)
        
        #Rewrite lines in config
        path = pathlib.Path(rmgc_config)
        data = yaml.safe_load(path.read_text())
        data["outpath"]  = os.path.dirname(self.outBase) + "/redmagic/"
        data["catfile"]  = os.path.dirname(self.outBase) + f"/{obase}_run_redmapper_v{rm_version}_lgt20_vl02_catalog.fit"
        data["redmagic_constchis"]    = [8.0, 8.0]
        data["redmagic_use_constchi"] = True
        data["redmagic_etas"]   = [0.5, 1.0]
        data["redmagic_n0s"]    = [10.0, 4.0]
        data["redmagic_names"]  = ['highdens', 'highlum']
        data["redmagic_zmaxes"] = [0.75, 0.95]
        data["redmagicfile"]    = self.outBase + '_redmagic_calib.fit'
        data["hpix"]            = self.make_calibration_hpix()
        data["nside"]           = self.nside_split

        path.write_text(yaml.safe_dump(data, sort_keys=False))

        if self.calib_dir is None:
            calib = redmapper.redmagic.RedmagicCalibrator(rmgc_config)
            calib.run(do_run = False)
        else:
            shutil.copy(self.calib_dir + f'/redmagic/{obase}_run_redmagic_calib.fit', 
                        os.path.dirname(self.outBase) + f'/redmagic/{obase}_run_redmagic_calib.fit')
            print("COPIED REDMAGIC CALIBRATION OVER FROM", self.calib_dir)

            shutil.copy(self.calib_dir + '/redmagic/run_default_run.yaml', 
                        os.path.dirname(self.outBase) + '/redmagic/run_default_run.yaml')

            path = pathlib.Path(os.path.dirname(self.outBase) + '/redmagic/run_default_run.yaml')
            data = yaml.safe_load(path.read_text())

            for k in data:
                
                if isinstance(data[k], str):
                    data[k] = data[k].replace(self.calib_dir, os.path.dirname(self.outBase))
                
                elif isinstance(data[k], list):

                    if len(data[k]) == 0: continue

                    if isinstance(data[k][0], str):
                        data[k] = [x.replace(self.calib_dir, os.path.dirname(self.outBase)) for x in data[k]]
                
            path.write_text(yaml.safe_dump(data, sort_keys=False))

            print("COPIED REDMAGIC CONFIG OVER FROM", self.calib_dir)

    @timeit
    def generate_redmagic(self):

        rmgc_config  = os.path.dirname(self.outBase) + '/redmagic/run_default_run.yaml'
        obase        = self._get_outbase_name()
        
        #Rewrite lines in config
        path = pathlib.Path(rmgc_config)
        data = yaml.safe_load(path.read_text())
        data["redmagicfile"]  = os.path.dirname(self.outBase) + f'/redmagic/{obase}_run_redmagic_calib.fit'
        path.write_text(yaml.safe_dump(data, sort_keys=False))
        
        run_redmagic = redmapper.redmagic.RunRedmagicTask(rmgc_config)
        run_redmagic.run(n_randoms = 20_000_000, clobber = True)



if __name__ == '__main__':

    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument("--outdir",             action='store', type=str, required=True)
    parser.add_argument("--input_catalog_hdf5", action='store', type=str, required=True)
    parser.add_argument("--input_specz",        action='store', type=str, required=True)
    parser.add_argument("--fracdet_map",        action='store', type=str, required=True)
    parser.add_argument("--foreground_map",     action='store', type=str, required=True)
    parser.add_argument("--SPmap_path",         action='store', type=str, required=True)
    parser.add_argument("--n_jobs",             action='store', type=int, required=True)
    parser.add_argument("--survey",             action='store', type=str, required=True)
    parser.add_argument("--config_override",    action='store', type=str, required=False, default = None)

    parser.add_argument("--SPmap_names",        action='store', type=str, default = "maglim,fwhm,airmass,exptime,skybrite")
    parser.add_argument("--seed",               action='store', type=int, default = 42)
    parser.add_argument("--calib_dir",          action='store', type=str, default = None)
    parser.add_argument("--bands",              action='store', type=str, default = "U,G,R,I,Z,Y,F106,F129,F158,F184")
    parser.add_argument("--bands_inds",         action='store', type=str, default = "0,1,2,3,4,5,6,7,8,9")
    parser.add_argument("--refband",            action='store', type=str, default = 'F184')
    parser.add_argument("--color_presel_thresh",action='store', type=str, default = '0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2')
    parser.add_argument("--z_range",            action='store', type=str, default = '0.1,0.95')
    parser.add_argument("--zeropoint",          action='store', type=str, default = '22.5')


    args = vars(parser.parse_args())

    os.environ['TMPDIR'] = args['outdir']

    Runner = BaseRunner
    
    os.makedirs(args['outdir'], exist_ok = True)
    Runner(outBase    = os.environ['TMPDIR'] + '/Eli', 
           calib_dir  = args['calib_dir'],
           bands      = args['bands'].split(','), 
           bands_inds = [int(b) for b in args['bands_inds'].split(',')],
           refband    = args['refband'],
           survey     = args['survey'],
           z_range    = [float(z) for z in args['z_range'].split(',')],
           zeropoint  = float(args['zeropoint']),
           
           input_catalog_hdf5 = args['input_catalog_hdf5'],
           input_specz        = args['input_specz'],
           fracdet_map        = args['fracdet_map'],
           foreground_map     = args['foreground_map'],
           SPmap_path         = args['SPmap_path'],
           SPmap_names        = args['SPmap_names'].split(','),
           config_override    = args['config_override'],
           
           n_jobs     = args['n_jobs'],
           seed       = args['seed'],

           color_presel_thresh = [float(c) for c in args['color_presel_thresh'].split(',')]
           ).go()
